//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_FB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FB_Login
    {
        public long id { get; set; }
        public string providename { get; set; }
        public string name { get; set; }
        public string emailid { get; set; }
    }
}
